# The Site Configuration
# Chirpy 主题基础配置

lang: zh-CN
timezone: Asia/Shanghai

title: 我的技术博客
description: >- # used by seo meta and the atom feed
  大模型全栈技术分享

url: "https://liangsh0208.github.io"

author:
  name: liangshihao
  url: https://liangsh0208.github.io

# 直接通过 Gem 加载主题
theme: jekyll-theme-chirpy

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-include-cache

# 文章设置
paginate: 10
