# 站点基础设置
title: 我的技术博客
description: 大模型全栈技术分享
url: "https://liangshihao.github.io" # 站点 URL
author: liangshihao

# 主题选择（官方预置，直接生效）
# 可选: minima, 默认为 minima，也可以从远程仓库引入主题
theme: minima

# 文章列表分页（可选，如果装了 jekyll-paginate 插件）
paginate: 5
paginate_path: "/blog/page:num/"

# 导航栏页面
header_pages:
  - about.md
  - categories.md
